#file: noinspection YAMLSchemaValidation
schema-version: v2
kind: action
metadata:
  name: setup-stackspot-workflows
  display-name: StackSpot Setup Workflows.
  description: Action to configure Stackspot workflows in SCM provider
  version: 0.0.1
spec: 
  type: python
  inputs:
    - label: SCM provider
      name: provider
      type: text
      items:
        - Azure
        - BitBucket
        - Github
        - Gitlab

    - label: Create Repository
      name: create_repo
      type: bool

    - label: Personal Access Token
      name: pat
      type: password
      condition:
        variable: provider
        operator: containsAny
        value:
          - Azure
          - Github
          - Gitlab

    - label: Project Name
      name: project_name
      type: text
      condition:
        variable: provider
        operator: containsAny
        value:
          - Azure
          - Gitlab

    - label: Organization Name
      name: org_name
      type: text
      condition:
        variable: provider
        operator: containsAny
        value:
          - Azure
          - Github

    - label: Personal Access Token (Github)
      name: github_pat
      type: password
      condition:
        variable: provider
        operator: containsAny
        value:
          - Azure

    - label: Repository Name
      name: repo_name
      type: text
      condition:
        variable: provider
        operator: containsAny
        value:
          - Github

    - label: Group Name
      name: group_name
      type: text
      condition:
        variable: provider
        operator: containsAny
        value:
          - Gitlab

    # - label: Workspace Name
    #   name: workspace_name
    #   type: text
    #   help: 'Inform your Workspace Name (e.g.: stack-spot)'
    #   condition:
    #     variable: provider
    #     operator: ==
    #     value: BitBucket

    # - label: Client Key
    #   name: client_key
    #   type: text
    #   condition:
    #     variable: provider
    #     operator: "=="
    #     value: BitBucket
    # - label: Client Secret
    #   name: client_secret
    #   type: password
    #   condition:
    #     variable: provider
    #     operator: "=="
    #     value: BitBucket
     # Field self_hosted_pool_name is asked when use_self_hosted_pool is true on setup.py

  python:
    script: stackspot-actions/setup-stackspot-workflows/main.py