#file: noinspection YAMLSchemaValidation
schema-version: v2
kind: action
metadata:
  name: setup-stackspot-workflows
  display-name: StackSpot Setup Workflows.
  description: Action to configure Stackspot workflows in SCM provider
  version: 0.0.1
spec: 
  type: python
  inputs:
    - label: SCM provider
      name: provider
      type: text
      items:
        - Azure
        - Bitbucket
        - Github
        - Gitlab

    - label: Personal Access Token
      name: pat
      type: password
      condition:
        variable: provider
        operator: containsAny
        value:
          - Azure
          - Github
          - Gitlab

    - label: Project Name
      name: project_name
      type: text
      condition:
        variable: provider
        operator: containsAny
        value:
          - Azure
          - Gitlab

    - label: Project Key
      name: project_key
      type: text
      condition:
        variable: provider
        operator: containsAny
        value:
          - Bitbucket

    - label: Organization Name
      name: org_name
      type: text
      condition:
        variable: provider
        operator: containsAny
        value:
          - Azure
          - Github

    - label: Repository Name
      name: repo_name
      type: text
      condition:
        variable: provider
        operator: containsAny
        value:
          - Github
          - Bitbucket
          - Azure

    - label: Group Name
      name: group_name
      type: text
      condition:
        variable: provider
        operator: containsAny
        value:
          - Gitlab

    - label: Is on premise?
      name: is_on_premise
      type: bool
      default: false
      condition:
        variable: provider
        operator: containsAny
        value:
          - Gitlab

    - label: Workspace Name
      name: workspace_name
      type: text
      condition:
        variable: provider
        operator: containsAny
        value:
          - Bitbucket

    - label: Client Key
      name: client_key
      type: text
      condition:
        variable: provider
        operator: containsAny
        value:
          - Bitbucket

    - label: Client Secret
      name: client_secret
      type: password
      condition:
        variable: provider
        operator: containsAny
        value:
          - Bitbucket

    - label: Gitlab api domain
      name: gitlab_api_domain
      type: text
      default: gitlab.com
      condition:
        variable: is_on_premise
        operator: ==
        value: true

  python:
    script: stackspot-actions/setup-stackspot-workflows/main.py
