schema-version: v1
kind: plugin
metadata:
  name: setup-runner
  display-name: setup-runner
  description: Plugin to setup StackSpot workflows
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  repository: https://github.com/stack-spot/stackspot-workflows-action
  technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
    - Api
  inputs:
    - label: SCM provider
      name: provider
      type: text
      items:
        - Azure
        - Github
    - label: Organization Name
      name: org_name
      type: text
      help: 'Inform your resource name (e.g.: Client)'
    - label: Repository Name
      name: repo_name
      type: text
    - label: Create Repository
      name: create_repo
      type: bool
  hooks:
    # Render workflows templates
    - type: render-templates
      trigger: after-render
      path: workflow-templates/azure
      condition:
        variable: provider
        operator: ==
        value: Azure

    - type: render-templates
      trigger: after-render
      path: workflow-templates/github
      condition:
        variable: provider
        operator: ==
        value: Github