schema-version: v1
kind: plugin
metadata:
  name: setup-runner
  display-name: setup-runner
  description: Plugin to setup StackSpot workflows
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  repository: https://github.com/stack-spot/stackspot-workflows-action
  technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
    - Api
  inputs:
    - label: SCM provider
      name: provider
      type: text
      items:
        - Azure
        - BitBucket
        - Github
        - Gitlab
    - label: Do you want to use self-hosted runners to run StackSpot workflows?
      name: use_self_hosted_pool
      type: bool
      default: false
    - label: Which self-hosted runner group do you want to use?
      name: self_hosted_pool_name
      type: text
      condition:
        variable: use_self_hosted_pool
        operator: ==
        value: true
  hooks:
    # Render workflows templates
    - type: render-templates
      trigger: after-render
      path: workflow-templates/azure
      condition:
        variable: provider
        operator: ==
        value: Azure

    - type: render-templates
      trigger: after-render
      path: workflow-templates/github
      condition:
        variable: provider
        operator: ==
        value: Github

    - type: render-templates
      trigger: after-render
      path: workflow-templates/bitbucket
      condition:
        variable: provider
        operator: ==
        value: BitBucket

    - type: render-templates
      trigger: after-render
      path: workflow-templates/gitlab
      condition:
        variable: provider
        operator: ==
        value: gitlab