schema-version: v1
kind: action
metadata:
  name: stakspot-gh-mk-repo-with-secrts
  display-name: Stackspot Create GitHub Repo With Secrets
  description: Action to create github repository With Secrets
  version: 1.0.1
spec:
  type: python
  about: docs/about.md
  usage: docs/usage.md
  release-notes: docs/release-notes.md
  implementation: docs/implementation.md
  inputs:
    - label: Visibility
      name: visibility
      type: text
      required: true
      items: 
        - public
        - internal
        - private
      help: "Internal repo can only be created by enterprise accounts."
    - label: Do you want to set stackspot credentials to secret on that repository?
      name: secret
      type: bool
      help: "Private repos can only have secrets on enterprise accounts."
    - label: Client Id
      name: client_id
      type: text
      condition:
        variable: secret
        operator: ==
        value: true
      help: This value will be set as repository secret
    - label: Client Key
      name: client_key
      type: password
      condition:
        variable: secret
        operator: ==
        value: true
      help: This value will be set as repository secret
    - label: Client Realm
      name: client_realm
      type: text
      help: This value will be set as repository secret
      condition:
        variable: secret
        operator: ==
        value: true
  python:
    workdir: .
    script: script.py
