{% raw -%}
trigger:
- none

name: ${{ parameters.correlation_id }}

parameters:
  - name: correlation_id
    displayName: Correlation id
    type: string
  - name: infra
    displayName: Json objet with create data
    type: string
  - name: cli_login
    displayName: CLI login (json)
    type: string
  - name: workspace_slug
    displayName: Workspace name
    type: string
  - name: actions
    displayName: Actions (json)
    type: string

resources:
  repositories:
    - repository: templates
      type: github
      name: stack-spot/stackspot-workflows-action
      endpoint: stackspot_github_connection

pool:
{% endraw %}
  {% if use_self_hosted_pool %}
  name: {{ self_hosted_pool_name }}
  {%- else %}
  vmImage: ubuntu-latest
  {%- endif %}
{% raw %}

jobs:
  - job:
    displayName: create-infra
    steps:
      - template: .azure/create.yml@templates
        parameters:
          correlation_id: ${{ parameters.correlation_id }}
          create: ${{ parameters.infra }}
          create_type: infra
          cli_login: ${{ parameters.cli_login }}
          workspace_slug: ${{ parameters.workspace_slug }}
          actions: ${{ parameters.actions }}
{% endraw %}