{%- raw -%}
trigger:
- none

name: ${{ parameters.correlation_id }}

parameters:
  - name: correlation_id
    displayName: Correlation id
    type: string
  - name: job_display_name
    displayName: Job display name
    type: string
  - name: api_inputs
    displayName: Json object with api data
    type: string
  - name: job_template
    displayName: Job template
    type: string
  - name: resource_repositories_ref
    displayName: Resource repository ref
    type: string

pool:
  name: default

jobs:
  - job:
    displayName: ${{ parameters.job_display_name }}
    steps:
      - bash: |
          execution_id=$(echo '${{ parameters.api_inputs }}' | jq -cr '.execution_id')
          export HTTP_ENABLE_FILE_DEBUG=false
      
          http_code=$(curl -s -o script.sh -w '%{http_code}' https://workflow-api.v1.stackspot.com/workflows/$execution_id --header 'Authorization: Bearer $(secret_stk_login)';)
          if [[ "$http_code" -ne "200" ]]; then
              echo "------------------------------------------------------------------------------------------"
              echo "---------------------------------------- Debug Starting ----------------------------------"
              echo "------------------------------------------------------------------------------------------"
      
              echo "HTTP_CODE:" $http_code
              echo "RESPONSE_CONTENT:"
              cat script.sh
      
              echo "------------------------------------------------------------------------------------------"
              echo "---------------------------------------- Debug Ending ------------------------------------"
              echo "------------------------------------------------------------------------------------------"
          else
              chmod +x script.sh
      
              echo "------------------------------------------------------------------------------------------"
              echo "---------------------------------------- Starting ----------------------------------------"
              echo "------------------------------------------------------------------------------------------"
      
              bash script.sh
      
              echo "------------------------------------------------------------------------------------------"
              echo "----------------------------------------  Ending  ----------------------------------------"
              echo "------------------------------------------------------------------------------------------"
          fi
{% endraw %}