name: 'Install STK CLI Action'
description: 'GitHub action to install STK CLI'

inputs:
  stk:
    description: stk cli name
    required: true
  email:
    description: user email to auth
    required: true
  pat:
    description: jwt to access
    required: true
  realm:
    description: account realm
    required: true

runs:
  using: "composite"
  steps:
    - name: Login
      shell: bash
      run: |
        export STK_CHANNEL=REMOTE
        echo -e "${{ inputs.stk}} login ${{ inputs.email}} --pat ${{ inputs.pat}} --realm ${{ inputs.realm}}\n" 
        ${{ inputs.stk}} login ${{ inputs.email}} --pat ${{ inputs.pat}} --realm ${{ inputs.realm}}
