schema-version: v1
kind: action
metadata:
  name: create-repo-bitbucket
  display-name: create-repo-bitbucket
  description: Create new bitbucket project and repository
  version: 0.0.1
spec:
  type: python
  about: docs/about.md
  usage: docs/usage.md
  release-notes: docs/release-notes.md
  requirements: docs/requirements.md
  implementation: docs/implementation.md
  inputs:
    - label: Bitbucket project name
      name: project_name
      type: text
      required: true
      help: Input the Bitbucket devOps project name, if it does not exist it will be created
  python:
    workdir: .
    script: script.py
