name: 'Install STK CLI Action'
description: 'GitHub action to install STK CLI'

inputs:
  stk:
    description: stk cli name
    required: true

runs:
  using: "composite"
  steps:
    - name: Cleanup
      shell: bash
      run: |
        rm -rf ~/.${{ inputs.stk}}
    - name: Install STK 
      shell: bash
      run: |
        curl -O -s https://stk.stackspot.com/installer/linux/${{ inputs.stk}} && \
        chmod +x ./${{ inputs.stk}} && \
        ./${{ inputs.stk}} --version
    - name: Configure path
      shell: bash
      run: |
        echo "PATH=$PATH:~/.${{ inputs.stk}}/bin" >> $GITHUB_ENV
    - name: Generate .env for QA if is stk-alpha
      if: inputs.stk == 'stk-alpha'
      shell: bash
      run: |
        wget https://stk-dev.stackspot.com/env/alpha-qa.env 
        mv alpha-qa.env ~/.stk-alpha/.env
        echo "STK_CLI_TEST=true" >> $GITHUB_ENV
        
