schema-version: v2
kind: action
metadata:
  name: stakspot-github-create-repository
  display-name: Stackspot Create GitHub Repository
  description: Action to create github repository if not exists
  version: 1.0.2
spec:
  type: python
  about: docs/about.md
  usage: docs/usage.md
  release-notes: docs/release-notes.md
  implementation: docs/implementation.md
  inputs:
    - label: Visibility
      name: visibility
      type: text
      required: true
      items: 
        - public
        - internal
        - private
      help: "Internal repo can only be created by enterprise accounts."
  python:
    workdir: .
    script: script.py
