schema-version: v2
kind: action
metadata:
  name: stakspot-github-create-repository
  display-name: Stackspot Create GitHub Repository
  description: Action to create github repository if not exists
  version: 1.0.2
spec:
  type: python
  inputs:
  - label: Visibility
    name: visibility
    type: text
    required: true
    items:
    - public
    - internal
    - private
    help: Internal repo can only be created by enterprise accounts.
  - label: Repository name
    name: name
    type: text
    required: true
    help: Input the repository name, if it does not exist it will be created
  python:
    workdir: .
    script: script.py
  docs:
    pt_br: docs/pt_br/doc.md
    en_us: docs/en_us/doc.md
